### ISSUE TITLE
Installation error using pip3

### ISSUE THREAD

**Issue by lawlawlaw** [commerceblock/pymainstay#2]
```pip3 install mainstay```
Results in the following error:
```ERROR: Could not find a version that satisfies the requirement mainstay (from versions: none)```
```ERROR: No matching distribution found for mainstay```

**Comment by tomt1664** [comment]
Still need to finalise this.

**Comment by tomt1664** [comment]
package name: pymainstay e1cb73d4828747d881bb3fe75b01539dc9c7a14a
